version: '3'
services:
  php:
    build: './php'
    volumes:
      - './:/var/www/html'
  nginx:
    image: nginx:latest
    volumes:
      - './:/var/www/html'
      - './:/etc/nginx/conf.d'
    ports:
      - 80:80
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=edudb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=111
    ports:
      - "5432:5432"
